### ISSUE TITLE
时长没有改变

### ISSUE THREAD

**Issue by zhourx1129** [z5882852/unipus-tool#1]
大佬，项目正常跑，且没有其他设备登录u校园，但是时长却没有增加。

**Comment by z5882852** [comment]
你好，能否提供运行的截图或者ws返回的信息？

**Comment by zhourx1129** [comment]
大佬，已经好了，当时我频繁的在浏览器和脚本之间进行切换可能是被限制了。浏览器清除了缓存后过段时间就可以了。
