### ISSUE TITLE
连接异常： [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

### ISSUE THREAD

**Issue by UPman24** [z5882852/unipus-tool#2]

**Comment by UPman24** [comment]
有个建议，题库用GPT4答题效果还挺不错，基本就只错一个，大部分情况不会错

**Comment by z5882852** [comment]
在linux或Mac上websocket连接可能会出现certificate verify failed: unable to get local issuer certificate 错误，在初始化WS时加入sslopt={"cert_reqs": ssl.CERT_NONE}参数即可解决
