### ISSUE TITLE
登陆成功后选择课程后报错

### ISSUE THREAD

**Issue by Violiate** [z5882852/unipus-tool#4]
![image](https://github.com/z5882852/unipus-tool/assets/166909042/bd83290e-ed8c-44b1-80d8-b701f489243e)

Traceback (most recent call last):
  File "G:\unipus-tool-main\main.py", line 98, in <module>
    ws_connect(open_id, auth_token, tutorial_id, 5)
  File "G:\unipus-tool-main\ws.py", line 17, in ws_connect
    ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.CERT_NONE})
TypeError: __init__() got an unexpected keyword argument 'sslopt'

**Comment by z5882852** [comment]
安装websocket-client库试试`pip install websocket-client`

**Comment by Violiate** [comment]
搞定了，多谢大佬

**Comment by Violiate** [comment]
搞定了，多谢大佬
